<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="57804" started-at="2019-07-01T10:27:22Z" finished-at="2019-07-01T10:28:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="57804" started-at="2019-07-01T10:27:22Z" finished-at="2019-07-01T10:28:20Z">
      <class name="com.training.sanity.tests.RETC_012">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.RETC_012@47c62251]" name="setUpBeforeClass" is-config="true" duration-ms="12" started-at="2019-07-01T10:27:22Z" finished-at="2019-07-01T10:27:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.RETC_012@47c62251]" name="setUp" is-config="true" duration-ms="29193" started-at="2019-07-01T10:27:22Z" finished-at="2019-07-01T10:27:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Test_RETC_012()[pri:0, instance:com.training.sanity.tests.RETC_012@47c62251]" name="Test_RETC_012" duration-ms="26681" started-at="2019-07-01T10:27:52Z" finished-at="2019-07-01T10:28:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[validation failed without try catch expected [A confirmation link has been sent to your email address] but found [Invalid password reset link.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: validation failed without try catch expected [A confirmation link has been sent to your email address] but found [Invalid password reset link.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.training.sanity.tests.RETC_012.Test_RETC_012(RETC_012.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_RETC_012 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.RETC_012@47c62251]" name="tearDown" is-config="true" duration-ms="1890" started-at="2019-07-01T10:28:18Z" finished-at="2019-07-01T10:28:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.RETC_012 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
